apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.storage.redisPVC_capacity }}
  hostPath:
    path: /data/redis-pv/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - "ReadWriteOnce"
  volumeName: redis-pv
  resources:
    requests:
      storage: {{ .Values.storage.redisPVC_request }}