apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-db
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
            role: master
    template:
        metadata:
            labels:
                app: redis
                role: master
        spec:
            volumes:
            - name: redis-storage
              persistentVolumeClaim:
                claimName: redis-pvc
            containers:
                - name: redis-master
                  image: {{ .Values.image.redis }}
                  resources:
                      limits:
                          cpu: 200m
                          memory: 200Mi
                  command:
                      - redis-server
                  args:
                      - --requirepass
                      - $(REDIS_PASSWORD)
                  ports:
                      - containerPort: {{ .Values.port.redis }}
                  env:
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: {{ .Values.secretKey.redis }}
                            key: db_password

---

apiVersion: v1
kind: Service
metadata:
    name: redis-db-service
    namespace: {{ .Values.namespace }}
    labels:
        app: redis
        role: master
spec:
    ports:
        - port: {{ .Values.port.redis }}
          targetPort: {{ .Values.port.redis }}
    selector:
        app: redis
        role: master