version: '3.8'

services:
  model:
    # Build the training service
    build:
      context: model
      dockerfile: Dockerfile
    image: model-server
    container_name: model-server-service
    ports:
      - 9000:9000
    restart: on-failure

  web:
    # Build the evaluation service
    build:
      context: web
      dockerfile: Dockerfile
    image: web-server
    container_name: web-server-service
    ports:
      - 8000:8000
    restart: on-failure

  redis:
    image: 'redis:latest'
    container_name: redis-db-service
    ports:
      - 6379:6379
    restart: on-failure