namespace: default

appName:
  model: 'model-serve'
  web: 'web-serve'

model: "gpt2"

configMap:
  modelServer: "model-config-v1.0"
  redis: "redis-config-v1.0"

secretKey:
  redis: "redis-secret-v1.0"

image:
  modelServer: "model-server:latest"
  webServer: "web-server:latest"
  redis: "redis:7.2.1"

port:
  modelServer: 9000
  webServer: 8000
  redis: 6379

storage:
  redisPVC_capacity : 10Gi
  redisPVC_request : "5Gi"

hostname: "fastapi.localhost"

db_password: cmVhbGx5ZGlmZmljdWx0cGFzc3dvcmQ=